name: PxyTech
version: 0.1
description: Extended functionality for p-xy's server
author: p-xy
website: https://github.com/p-xy

main: io.github.pxy.pxytech.PxyTech

commands:
  afk:
    description: Set yourself as AFK, wears off on activity
    usage: /afk [reason]
  reply:
    description: Message the last player who messaged you
    usage: /reply <message>
  quirks:
    description: Displays a list of the quirks in play
    usage: /quirks